#
#  Example Makefile for building the jsoncbor example
#

CC = gcc
LD = $(CC)
CFLAGS = -std=c99 -Wall -Wextra -O2
CFLAGS += -Isrc -Iextras/cbor  # for combined sources
LDFLAGS = -lm

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

OBJECTS = src/duktape.o extras/cbor/duk_cbor.o extras/cbor/jsoncbor.o

jsoncbor: $(OBJECTS)
	$(LD) -o $@ $(OBJECTS) $(LDFLAGS)

all: jsoncbor

clean:
	$(RM) $(OBJECTS) jsoncbor
