CC = gcc
LD = $(CC)

RM = rm -f

CFLAGS = -std=c99 -Wall -Wextra -O2 -Isrc
LDFLAGS = -lm

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

OBJECTS = src/duktape.o examples/codepage-conv/duk_codepage_conv.o \
	examples/codepage-conv/test.o

codepage: $(OBJECTS)
	$(LD) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	$(RM) $(OBJECTS) codepage
