#
#  Example Makefile for building the minimal eventloop example
#

CC = gcc

timers:
	$(CC) -o $@ -std=c99 -Wall -Wextra -O2 -Isrc -Iextras/console \
		examples/timers/main.c \
		examples/timers/eventloop.c \
		examples/timers/fileio.c \
		src/duktape.c \
		extras/console/duk_console.c \
		-lm
