#
#  Example Makefile for building the eventloop example
#

CC = gcc
LD = $(CC)

evloop: $(OBJECTS)
	@echo "NOTE: The eventloop is an example intended to be used on Linux"
	@echo "      or other common UNIX variants.  It is not fully portable."
	@echo ""

	$(LD) -o $@ $(OBJECTS) $(LDFLAGS)

	@echo ""
	@echo "NOTE: You must 'cd examples/eventloop' before you execute the"
	@echo "	  eventloop binary: it relies on finding .js files in CWD"

clean:
	$(RM) $(OBJECTS) evloop
