#
#  Example Makefile for building the sandbox example
#

CC = gcc
LD = $(CC)
CFLAGS = -std=c99 -Wall -Wextra -O2
CFLAGS += -Isrc  # for combined sources
LDFLAGS = -lm

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

OBJECTS = src/duktape.o examples/sandbox/sandbox.o

sandbox: $(OBJECTS)
	$(LD) -o $@ $(OBJECTS) $(LDFLAGS)

all: sandbox

clean:
	$(RM) $(OBJECTS) sandbox
