#
#  Example Makefile for building the eventloop example
#

evloop:
	gcc -o $@ -std=c99 -Wall -Wextra -O2 -Isrc \
		examples/eventloop/main.c \
		examples/eventloop/c_eventloop.c \
		examples/eventloop/poll.c \
		examples/eventloop/socket.c \
		examples/eventloop/fileio.c \
		examples/eventloop/ncurses.c \
		src/duktape.c \
		-lm -lncurses

	@echo "NOTE: you must 'cd examples/eventloop' before you execute the"
	@echo "      eventloop binary: it relies on finding .js files in CWD"
