#
#  Example Makefile for building the jxpretty example
#

CC = gcc
LD = $(CC)
CFLAGS = -std=c99 -Wall -Wextra -O2
CFLAGS += -Isrc  # for combined sources
LDFLAGS = -lm

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

OBJECTS = src/duktape.o examples/jxpretty/jxpretty.o

jxpretty: $(OBJECTS)
	$(LD) -o $@ $(OBJECTS) $(LDFLAGS)

all: jxpretty

clean:
	$(RM) $(OBJECTS) jxpretty
