# FIXME: placeholder

import os

#import sconstools.rst2html

docs = [
	'datetime.txt',
	'json.txt',
	'regexp.txt',
	'sorting.txt'
]

for doc in docs:
	target = os.path.splitext(doc)[0] + '.html'
	Command(target, doc, 'rst2html $SOURCE $TARGET')

