# Shared config options for "make duk" and "make dukd".
# Some commented out options are kept so that it's easy to
# tweak common development time options manually.

# If an unknown option is used, configure.py/genconfig.py will warn about it.
#DUK_USE_SOME_UNKNOWN_OPTION: true

DUK_USE_TARGET_INFO: "\"duk command built from Duktape repo\""

DUK_USE_FATAL_HANDLER:
  verbatim: "#define DUK_USE_FATAL_HANDLER(udata,msg) do { const char *fatal_msg = (msg); fprintf(stderr, \"*** FATAL ERROR: %s\\n\", fatal_msg ? fatal_msg : \"no message\"); *((volatile unsigned int *) 0) = (unsigned int) 0xdeadbeefUL; abort(); } while(0)"
DUK_USE_SELF_TESTS: true

#DUK_USE_ASSERTIONS: true

#DUK_USE_PACKED_TVAL: false
#DUK_USE_ALIGN_BY: 4
#DUK_USE_ALIGN_BY: 8
#DUK_USE_REFERENCE_COUNTING: false
#DUK_USE_MARK_AND_SWEEP: false
#DUK_USE_VOLUNTARY_GC: false

#DUK_USE_TRACEBACKS: false
#DUK_USE_PC2LINE: false
#DUK_USE_VERBOSE_ERRORS: false
#DUK_USE_PARANOID_ERRORS: true
#DUK_USE_AUGMENT_ERRORS: false
#DUK_USE_GC_TORTURE: true
#DUK_USE_SHUFFLE_TORTURE: true
#DUK_USE_REFZERO_FINALIZER_TORTURE: true
#DUK_USE_MARKANDSWEEP_FINALIZER_TORTURE: true
#DUK_USE_STRICT_DECL: false
#DUK_USE_REGEXP_SUPPORT: false
#DUK_USE_ES6_REGEXP_SYNTAX: false
#DUK_USE_OCTAL_SUPPORT: false
#DUK_USE_SOURCE_NONBMP: false
#DUK_USE_STRICT_UTF8_SOURCE: true
#DUK_USE_SECTION_B: false

DUK_USE_INTERRUPT_COUNTER: true
DUK_USE_DEBUGGER_SUPPORT: true
DUK_USE_DEBUGGER_FWD_LOGGING: true
DUK_USE_DEBUGGER_DUMPHEAP: true
DUK_USE_DEBUGGER_INSPECT: true
#DUK_USE_DEBUGGER_THROW_NOTIFY: false
#DUK_USE_DEBUGGER_PAUSE_UNCAUGHT: false
#DUK_USE_DEBUGGER_TRANSPORT_TORTURE: true

#DUK_USE_JX: false
#DUK_USE_JC: false
#DUK_USE_NONSTD_GETTER_KEY_ARGUMENT: false
#DUK_USE_NONSTD_SETTER_KEY_ARGUMENT: false
#DUK_USE_NONSTD_FUNC_STMT: false
#DUK_USE_NONSTD_FUNC_CALLER_PROPERTY: true
#DUK_USE_NONSTD_FUNC_SOURCE_PROPERTY: true
#DUK_USE_NONSTD_ARRAY_SPLICE_DELCOUNT: false
#DUK_USE_NONSTD_ARRAY_CONCAT_TRAILER: false
#DUK_USE_NONSTD_ARRAY_MAP_TRAILER: false
#DUK_USE_NONSTD_JSON_ESC_U2028_U2029: false
#DUK_USE_NONSTD_STRING_FROMCHARCODE_32BIT: false
#DUK_USE_ES6_OBJECT_PROTO_PROPERTY: false
#DUK_USE_ES6_OBJECT_SETPROTOTYPEOF: false
#DUK_USE_ES6_PROXY: false
#DUK_USE_ZERO_BUFFER_DATA: false
#DUK_USE_SETJMP: true
#DUK_USE_UNDERSCORE_SETJMP: true
#DUK_USE_SIGSETJMP: true
#DUK_USE_CPP_EXCEPTIONS: true
#DUK_USE_LIGHTFUNC_BUILTINS: true
#DUK_USE_BUFFEROBJECT_SUPPORT: false

DUK_USE_FASTINT: true
DUK_USE_JSON_STRINGIFY_FASTPATH: true
